frr version 8.5
frr defaults traditional
hostname ce-b2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! Customer B — Site 2 (VRF-BLUE)
! Pre-configured. No routing config needed here.
!
interface lo
 ip address 10.20.0.2/32
!
interface eth1
 description to pe2 (VRF-BLUE)
 ip address 10.20.34.2/30
!
ip route 0.0.0.0/0 10.20.34.1
!
end
