frr version 8.5
frr defaults traditional
hostname r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ! Loopback - advertise into EIGRP
 ip address 10.0.0.3/32
!
interface eth1
 ! Link to asbr1: 10.2.10.0/30, r2=.2
 ! EIGRP AS 100
 ip address 10.2.10.2/30
!
interface eth2
 ! Link to asbr2: 10.2.20.0/30, r2=.1
 ! EIGRP AS 100
 ip address 10.2.20.1/30
!
! TODO: Configure EIGRP AS 100
!   router eigrp 100
!    network 10.0.0.3/32
!    network 10.2.10.0/30
!    network 10.2.20.0/30
!
end
