frr version 8.4_git
frr defaults traditional
hostname branch1
service integrated-vtysh-config
interface lo
 ip address 10.250.255.41/32
interface eth1
 ip address 10.250.0.15/31
interface eth2
 ip address 10.250.50.1/24
router ospf
 ospf router-id 10.250.255.41
 passive-interface default
 no passive-interface eth1
 network 10.250.0.14/31 area 0
 network 10.250.50.0/24 area 0
 network 10.250.255.41/32 area 0
end
