frr version 8.5
frr defaults traditional
hostname host-a
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ! Link to router: 192.168.1.0/30, host-a=.1
 ip address 192.168.1.1/30
!
! Default route pointing to router
ip route 0.0.0.0/0 192.168.1.2
!
end
