frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ! Loopback - advertise into OSPF
 ip address 10.0.0.5/32
!
interface eth1
 ! Link to asbr2: 10.1.30.0/30, r3=.2
 ! OSPF area 0 (right domain)
 ip address 10.1.30.2/30
!
! TODO: Configure OSPF
!   router ospf
!    router-id 10.0.0.5
!    network 10.0.0.5/32 area 0
!    network 10.1.30.0/30 area 0
!
end
