frr version 8.5
frr defaults traditional
hostname ce2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.100.2.1/32
!
interface eth1
 description to PE2
 ip address 192.168.20.1/30
!
router bgp 65002
 bgp router-id 10.100.2.1
 no bgp ebgp-requires-policy
 !
 neighbor 192.168.20.2 remote-as 65000
 neighbor 192.168.20.2 description pe2
 !
 address-family ipv4 unicast
  neighbor 192.168.20.2 activate
  network 10.100.2.1/32
 exit-address-family
!
end
