frr version 8.5
frr defaults traditional
hostname leaf2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.2/32

interface eth1
 ! Link to spine1 — 10.1.0.2/31 (leaf2=.2  spine1=.3)
 ip address 10.1.0.2/31

interface eth2
 ! Link to spine2 — 10.2.0.2/31 (leaf2=.2  spine2=.3)
 ip address 10.2.0.2/31

! -------------------------------------------------------
! YOUR TASK: Configure BGP AS65002 on leaf2
!
! router bgp 65002
!  no bgp ebgp-requires-policy
!  bgp router-id 10.0.0.2
!  bgp bestpath as-path multipath-relax
!  maximum-paths 2
!  neighbor 10.1.0.3 remote-as 65100
!  neighbor 10.2.0.3 remote-as 65200
!  !
!  address-family ipv4 unicast
!   network 10.0.0.2/32
!   neighbor 10.1.0.3 activate
!   neighbor 10.2.0.3 activate
! -------------------------------------------------------
