frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.3/32
!
interface eth1
 description to r2 (AS65002) — iBGP
 ip address 10.1.23.2/30
!
interface eth2
 description to r4 (AS65003) — eBGP
 ip address 10.1.34.1/30
!
router bgp 65002
 no bgp ebgp-requires-policy
 bgp router-id 10.0.0.3
 neighbor 10.1.23.1 remote-as 65002
 neighbor 10.1.34.2 remote-as 65003
 address-family ipv4 unicast
  neighbor 10.1.23.1 activate
  neighbor 10.1.34.2 activate
  neighbor 10.1.34.2 next-hop-self
  network 10.0.0.3/32
 exit-address-family
!
end
