frr version 8.5
frr defaults traditional
hostname host1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

! host1 is on the VXLAN L2 segment (VNI 100)
! eth1 connects to vtep1:eth2 which is enslaved to bridge br100
! Traffic from host1 is forwarded over VXLAN to host2 via vtep2

interface eth1
 ip address 172.16.0.1/24

ip route 0.0.0.0/0 172.16.0.254
