frr version 8.5
frr defaults traditional
hostname r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.0.2/30
!
router ospf
 network 10.0.0.0/30 area 0
!
end
