frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.3/32
!
interface eth1
 description to r2
 ip address 10.1.23.2/30
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 SecretKey123
!
router ospf
 ospf router-id 10.0.0.3
 network 10.0.0.3/32 area 0
 network 10.1.23.0/30 area 0
 passive-interface lo
!
end
