frr version 8.5
frr defaults traditional
hostname r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ! Loopback - advertise into OSPF
 ip address 10.0.0.1/32
!
interface eth1
 ! Link to asbr1: 10.1.10.0/30, r1=.1, asbr1=.2
 ! OSPF area 0 (left domain)
 ip address 10.1.10.1/30
!
! TODO: Configure OSPF
!   router ospf
!    router-id 10.0.0.1
!    network 10.0.0.1/32 area 0
!    network 10.1.10.0/30 area 0
!
end
