frr version 8.5
frr defaults traditional
hostname pe1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 192.168.0.1/32

interface eth1 vrf VRF-BLUE
 description to ce-a1 (should be RED — this is the bug)
 ip address 10.10.12.2/30

interface eth2 vrf VRF-RED
 description to pe2 RED inter-PE link
 ip address 10.10.99.1/30

interface eth3 vrf VRF-BLUE
 description to ce-b1 (BLUE)
 ip address 10.20.12.2/30

interface eth4 vrf VRF-BLUE
 description to pe2 BLUE inter-PE link
 ip address 10.20.99.1/30

ip route 10.10.0.1/32 10.10.12.1 vrf VRF-RED
ip route 10.10.0.2/32 10.10.99.2 vrf VRF-RED
ip route 10.20.0.1/32 10.20.12.1 vrf VRF-BLUE
ip route 10.20.0.2/32 10.20.99.2 vrf VRF-BLUE
