#!/bin/bash
# ============================================================
# Samba AD DC container entrypoint.
#
# Lab 01 (manual): AUTO_PROVISION is unset, so this just starts
# supervisord. SAMBA_AUTOSTART defaults to "false", so the samba
# daemon stays down until the student runs /provision.sh, which
# provisions the domain and then `supervisorctl start samba`.
#
# Labs 02+ (cumulative foundation): the override sets
# AUTO_PROVISION=true and SAMBA_AUTOSTART=true, so this script
# provisions and seeds the LAB.CORP domain on first boot (no manual
# step) and supervisord then auto-starts samba.
#
# Provisioning and seeding operate on the local sam.ldb directly and
# do NOT require the samba daemon to be running, so we do them before
# handing PID 1 to supervisord.
# ============================================================
set -e

REALM="${REALM:-LAB.CORP}"
NETBIOS="${NETBIOS:-LAB}"
ADMIN_PASS="${ADMIN_PASS:-P@ssw0rd1}"
DNS_FORWARDER="${DNS_FORWARDER:-8.8.8.8}"

# /etc/samba/smb.conf and /etc/krb5.conf live in the CONTAINER filesystem, but
# the provisioned domain (sam.ldb) lives in the dc1-data VOLUME. On any container
# recreate that reuses the volume (a plain `down`/`up`, no -v), the domain
# persists while these two files return as image defaults — leaving the AD daemon
# with `server role = standalone server`, so `samba` exits with "misconfigured
# 'server role'" and crash-loops (no KDC, no DNS, kinit fails). We therefore must
# (re)write these host-side files whenever the domain already exists, not only at
# first provision.
write_ad_smb_conf() {
    local netbios_name realm_lc
    netbios_name="$(hostname -s | tr '[:lower:]' '[:upper:]')"
    realm_lc="$(echo "${REALM}" | tr '[:upper:]' '[:lower:]')"
    cat > /etc/samba/smb.conf <<EOF
# Active Directory DC config — (re)generated by the entrypoint on boot because it
# lives in the container fs while the domain lives in the dc1-data volume.
[global]
	dns forwarder = ${DNS_FORWARDER}
	netbios name = ${netbios_name}
	realm = ${REALM}
	server role = active directory domain controller
	workgroup = ${NETBIOS}
	idmap_ldb:use rfc2307 = yes
	ntlm auth = mschapv2-and-ntlmv2-only

[sysvol]
	path = /var/lib/samba/sysvol
	read only = No

[netlogon]
	path = /var/lib/samba/sysvol/${realm_lc}/scripts
	read only = No
EOF
}

if [ "${AUTO_PROVISION}" = "true" ] && [ ! -f /var/lib/samba/private/sam.ldb ]; then
    echo "==> [entrypoint] Auto-provisioning ${REALM} (cumulative foundation)..."
    rm -f /etc/samba/smb.conf
    rm -rf /var/lib/samba/private/* /var/lib/samba/sysvol/*
    samba-tool domain provision \
        --realm="${REALM}" \
        --domain="${NETBIOS}" \
        --server-role=dc \
        --dns-backend=SAMBA_INTERNAL \
        --adminpass="${ADMIN_PASS}" \
        --option="dns forwarder = ${DNS_FORWARDER}" \
        --option="ntlm auth = mschapv2-and-ntlmv2-only"
    cp /var/lib/samba/private/krb5.conf /etc/krb5.conf

    echo "==> [entrypoint] Seeding foundation objects (Lab 01 equivalents)..."
    bash /usr/local/bin/seed-domain.sh
    echo "==> [entrypoint] Provision + seed complete."
elif [ "${AUTO_PROVISION}" = "true" ] && [ -f /var/lib/samba/private/sam.ldb ]; then
    # Existing domain from a prior container: the volume kept sam.ldb, but this
    # fresh container lost its host-side config. Regenerate it so the AD daemon
    # starts in the correct role. (seed-domain.sh is NOT re-run — the objects
    # already exist in the persisted directory.)
    echo "==> [entrypoint] Existing domain detected; regenerating smb.conf + krb5.conf..."
    write_ad_smb_conf
    if [ -f /var/lib/samba/private/krb5.conf ]; then
        cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
    fi
fi

# Optional hook for derived images (e.g. samba-ad-wazuh enables audit
# logging in smb.conf). Runs every boot, after any provisioning, before
# samba starts — hook scripts must be idempotent.
if [ -x /usr/local/bin/post-provision-hook.sh ]; then
    /usr/local/bin/post-provision-hook.sh
fi

exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
