[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:samba]
command=/usr/sbin/samba --foreground --no-process-group
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/samba-stdout.log
stderr_logfile=/var/log/supervisor/samba-stderr.log
