frr version 8.5
frr defaults traditional
hostname spine1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.101/32

interface eth1
 ip address 10.1.0.1/31

interface eth2
 ip address 10.1.0.3/31

interface eth3
 ip address 10.1.0.5/31

interface eth4
 ip address 10.1.0.7/31

router bgp 65100
 no bgp ebgp-requires-policy
 bgp router-id 10.0.0.101
 bgp bestpath as-path multipath-relax
 maximum-paths 4
 neighbor 10.1.0.0 remote-as 65001
 neighbor 10.1.0.2 remote-as 65002
 neighbor 10.1.0.4 remote-as 65003
 neighbor 10.1.0.6 remote-as 65004
 !
 address-family ipv4 unicast
  network 10.0.0.101/32
  neighbor 10.1.0.0 activate
  neighbor 10.1.0.2 activate
  neighbor 10.1.0.4 activate
  neighbor 10.1.0.6 activate
 exit-address-family
