frr version 8.5
frr defaults traditional
hostname ce-b1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! Customer B — Site 1 (VRF-BLUE)
! Pre-configured. No routing config needed here.
!
interface lo
 ip address 10.20.0.1/32
!
interface eth1
 description to pe1 (VRF-BLUE)
 ip address 10.20.12.1/30
!
ip route 0.0.0.0/0 10.20.12.2
!
end
