include /etc/nginx/modules-enabled/*.conf;

events {}

http {
    log_format lab 'event=$http_x_lab_event control=waf status=$status source=$remote_addr path=$uri';
    access_log syslog:server=10.114.60.10:514 lab;

    server {
        listen 8080;
        server_name _;
        modsecurity off;
        modsecurity_rules_file /etc/nginx/modsecurity-lab.conf;

        location / {
            proxy_set_header X-Lab-Event $http_x_lab_event;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_pass http://10.114.20.20:8080;
        }
    }
}
