#!/usr/bin/env python3
"""Regenerate anki/MANIFEST.md — the lab -> track work list.

A lab's primary track is the first docs/tracks/<track>/ directory containing a
page named after it; labs in more than one track are noted. Labs with no track
page land in `unsorted` and still need triage.
"""

import pathlib
import re
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
TRACKS = ROOT / "docs" / "tracks"

# Which extraction batch each track belongs to (matches the task list).
BATCH = {
    "ospf": 1, "bgp": 1, "eigrp": 1, "isis": 1, "route-control": 1, "mpls-sp": 1,
    "layer2": 2, "data-center": 2, "tunnels-vpn": 2, "high-availability": 2,
    "security": 3, "security-infrastructure": 3, "enterprise": 3,
    "operations": 3, "ot-iot": 3, "enterprise-it-101": 3,
    "debug": 4, "troubleshooting": 4,
    "unsorted": 5,
}


def main() -> None:
    lab_tracks: dict[str, list[str]] = defaultdict(list)
    for page in sorted(TRACKS.glob("*/*.md")):
        if page.stem == "index":
            continue
        lab_tracks[page.stem].append(page.parent.name)

    all_labs = sorted(p.name for p in (ROOT / "labs").iterdir()
                      if p.is_dir() and p.name != "fixtures")
    eit_labs = sorted(p.name for p in (ROOT / "enterprise-it-101" / "labs").iterdir()
                      if p.is_dir())

    rows = []
    for lab in all_labs:
        tracks = lab_tracks.get(lab) or ["unsorted"]
        rows.append((f"labs/{lab}", tracks[0], tracks[1:]))
    for lab in eit_labs:
        rows.append((f"enterprise-it-101/labs/{lab}", "enterprise-it-101", []))

    by_batch: dict[int, list] = defaultdict(list)
    for path, track, also in rows:
        by_batch[BATCH.get(track, 5)].append((path, track, also))

    out = [
        "# Card extraction manifest",
        "",
        "Generated by `anki/make_manifest.py`. Primary track comes from",
        "`docs/tracks/<track>/<lab>.md`; a lab listed under several tracks shows the",
        "extras in *also*. Tick a lab off once its cards are in `anki/cards/`.",
        "",
        f"**{len(rows)} labs total.**",
        "",
    ]
    names = {1: "Batch 1 — routing", 2: "Batch 2 — L2 / DC / VPN / HA",
             3: "Batch 3 — security / enterprise / ops", 4: "Batch 4 — debug & troubleshooting",
             5: "Batch 5 — unsorted (needs triage)"}
    for batch in sorted(by_batch):
        entries = by_batch[batch]
        out += [f"## {names[batch]} ({len(entries)} labs)", "",
                "| lab | track | also |", "|---|---|---|"]
        for path, track, also in sorted(entries):
            out.append(f"| `{path}` | {track} | {', '.join(also) or '—'} |")
        out.append("")

    (ROOT / "anki" / "MANIFEST.md").write_text("\n".join(out))
    print(f"wrote anki/MANIFEST.md — {len(rows)} labs")
    for batch in sorted(by_batch):
        print(f"  batch {batch}: {len(by_batch[batch])}")


if __name__ == "__main__":
    main()
