frr version 8.5
frr defaults traditional
hostname r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.1/32
 ! TODO: ip ospf area 0

interface eth1
 ip address 10.1.12.1/30
 ! TODO: ip ospf area 0
 ! TODO: ip ospf bfd
 ! TODO (optional): ip ospf bfd detect-multiplier 3
 ! TODO (optional): ip ospf bfd min-rx 300
 ! TODO (optional): ip ospf bfd min-tx 300

interface eth2
 ip address 10.1.13.1/30
 ! TODO: ip ospf area 0
 ! TODO: ip ospf bfd

! TODO: configure OSPF
! router ospf
!  router-id 10.0.0.1
