driver=wired
interface=eth3
ctrl_interface=/run/hostapd
ctrl_interface_group=0
logger_stdout=-1
logger_stdout_level=2
logger_syslog=-1
logger_syslog_level=2
ieee8021x=1
eapol_version=2
auth_server_addr=192.168.99.2
auth_server_port=1812
auth_server_shared_secret=testing123
acct_server_addr=192.168.99.2
acct_server_port=1813
acct_server_shared_secret=testing123
own_ip_addr=192.168.99.1
nas_identifier=wireless-auth-control-quarantine
