frr version 8.4_git
frr defaults traditional
hostname isp1
service integrated-vtysh-config
interface lo
 ip address 10.252.255.1/32
interface eth1
 ip address 192.0.2.1/31
interface eth2
 ip address 192.0.2.4/31
router bgp 64501
 bgp router-id 10.252.255.1
 no bgp ebgp-requires-policy
 neighbor 192.0.2.0 remote-as 65000
 neighbor 192.0.2.5 remote-as 64500
 address-family ipv4 unicast
  network 192.0.2.0/31
  neighbor 192.0.2.0 activate
  neighbor 192.0.2.5 activate
 exit-address-family
end
