frr version 8.4_git
frr defaults traditional
hostname core2
service integrated-vtysh-config
interface lo
 ip address 10.250.255.22/32
interface eth1
 ip address 10.250.0.2/31
interface eth2
 ip address 10.250.0.6/31
interface eth3
 ip address 10.250.0.9/31
interface eth4
 ip address 10.250.0.12/31
interface eth5
 ip address 10.250.0.14/31
router ospf
 ospf router-id 10.250.255.22
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 no passive-interface eth3
 no passive-interface eth4
 no passive-interface eth5
 network 10.250.0.2/31 area 0
 network 10.250.0.6/31 area 0
 network 10.250.0.8/31 area 0
 network 10.250.0.12/31 area 0
 network 10.250.0.14/31 area 0
 network 10.250.255.22/32 area 0
end
