frr version 8.5
frr defaults traditional
hostname ce-a1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.10.0.1/32

interface eth1
 description to pe1 (VRF-RED)
 ip address 10.10.12.1/30

ip route 0.0.0.0/0 10.10.12.2
