frr version 8.5
frr defaults traditional
hostname host-b
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface eth1
 ip address 192.168.2.10/24

ip route 0.0.0.0/0 192.168.2.1
