frr version 8.4_git
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 ip address 10.1.0.1/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.12.1/30
 ip ospf area 0
!
interface eth3
 ip address 172.16.0.1/30
!
router ospf
 ospf router-id 10.0.0.1
 network 10.0.0.1/32 area 0
 passive-interface eth1
 passive-interface eth3
!
