module(load="imudp")
input(type="imudp" port="514")

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction off

template(name="PerHost" type="string" string="/var/log/remote/%HOSTNAME%.log")
*.* ?PerHost
& stop
