frr version 8.5
frr defaults traditional
hostname host2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

! host2 is on the VXLAN L2 segment (VNI 100)
! eth1 connects to vtep2:eth2 which is enslaved to bridge br100
! Traffic from host2 is forwarded over VXLAN to host1 via vtep1

interface eth1
 ip address 172.16.0.2/24

ip route 0.0.0.0/0 172.16.0.254
