frr version 8.5
frr defaults traditional
hostname hub
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.1/32

interface dmvpn0
 ip address 172.16.0.1/24
 ip nhrp network-id 1
 ip nhrp redirect
 ip ospf network point-to-multipoint
 ip ospf area 0

router ospf
 router-id 10.0.0.1
 network 10.0.0.1/32 area 0
 passive-interface lo
