frr version 8.5
frr defaults traditional
hostname r4
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.4/32
!
interface eth1
 description to r3 (AS65002) — eBGP
 ip address 10.1.34.2/30
!
router bgp 65003
 no bgp ebgp-requires-policy
 bgp router-id 10.0.0.4
 neighbor 10.1.34.1 remote-as 65002
 address-family ipv4 unicast
  neighbor 10.1.34.1 activate
  network 10.0.0.4/32
 exit-address-family
!
end
