frr version 8.5
frr defaults traditional
hostname pe2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 192.168.0.2/32

interface eth1 vrf VRF-RED
 description to pe1 RED inter-PE link
 ip address 10.10.99.2/30

interface eth2 vrf VRF-RED
 description to ce-a2 (RED)
 ip address 10.10.34.1/30

interface eth3 vrf VRF-BLUE
 description to pe1 BLUE inter-PE link
 ip address 10.20.99.2/30

interface eth4 vrf VRF-BLUE
 description to ce-b2 (BLUE)
 ip address 10.20.34.1/30

ip route 10.10.0.1/32 10.10.99.1 vrf VRF-RED
ip route 10.10.0.2/32 10.10.34.2 vrf VRF-RED
ip route 10.20.0.1/32 10.20.99.1 vrf VRF-BLUE
ip route 10.20.0.2/32 10.20.34.2 vrf VRF-BLUE
