frr version 8.4_git
frr defaults traditional
hostname edge2
service integrated-vtysh-config
interface lo
 ip address 10.251.255.12/32
interface eth1
 ip address 10.251.0.3/31
 ip ospf network point-to-point
interface eth2
 ip address 10.251.0.5/31
interface eth3
 ip address 192.0.2.2/31
router ospf
 ospf router-id 10.251.255.12
 passive-interface default
 no passive-interface eth1
 network 10.251.0.2/31 area 0
 network 10.251.255.12/32 area 0
 default-information originate always metric 100
 redistribute bgp metric 100 route-map INTERNET-ONLY
router bgp 65000
 bgp router-id 10.251.255.12
 no bgp ebgp-requires-policy
 neighbor 10.251.0.4 remote-as 65000
 neighbor 192.0.2.3 remote-as 64502
 address-family ipv4 unicast
  neighbor 10.251.0.4 activate
 neighbor 192.0.2.3 activate
 exit-address-family
ip prefix-list INTERNET seq 10 permit 198.18.10.0/24
route-map INTERNET-ONLY permit 10
 match ip address prefix-list INTERNET
end
