frr version 8.4_git
frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface lo
 ip address 10.0.0.2/32
 ip ospf area 0
 ip ospf passive
!
interface eth1
 ip address 10.0.12.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.23.1/30
 ip ospf area 0
!
interface eth3
 ip address 172.16.0.5/30
 ip ospf passive
!
router ospf
 ospf router-id 10.0.0.2
!
