client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = localhost
}

client access1 {
    ipaddr = 192.168.100.1
    secret = testing123
    shortname = access1
    nas_type = other
}
