[libdefaults]
    default_realm = LAB.CORP
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false

[realms]
    LAB.CORP = {
        kdc = dc1.lab.corp
        admin_server = dc1.lab.corp
    }

[domain_realm]
    .lab.corp = LAB.CORP
    lab.corp = LAB.CORP
