frr version 8.5
frr defaults traditional
hostname r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.2/32

interface eth1
 description to r1
 ip address 10.1.12.2/30

interface eth2
 description to r4
 ip address 10.1.24.1/30

router eigrp 100
 eigrp router-id 10.0.0.2
 network 0.0.0.0/0
 passive-interface lo
