frr version 8.5
frr defaults traditional
hostname r4
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.4/32
 ip ospf passive
 ip ospf area 2
!
interface eth1
 description to r3
 ip address 10.1.34.2/30
 ip ospf area 2
!
router ospf
 ospf router-id 10.0.0.4
 area 2 stub
!
end
