frr version 8.5
frr defaults traditional
hostname r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! -------------------------------------------------------
! Node: r1  (Regular Area 1 router)
!
! This router lives entirely in OSPF Area 1.
! It has no ABR responsibilities.
!
! What you need to configure here:
!   - OSPF process "CORE" with router-id 10.0.0.1
!   - ip ospf area 1 on eth1 (link to r2)
!   - ip ospf area 1 on lo, marked passive
! Hint:
!   interface lo
!    ip ospf passive
!    ip ospf area 1
!   !
!   interface eth1
!    ip ospf area 1
!   !
!   router ospf
!    ospf router-id 10.0.0.1
! -------------------------------------------------------
!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 description to r2
 ip address 10.1.12.1/30
!
end
