frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.3/32

interface eth1
 description to r1
 ip address 10.1.13.2/30

interface eth2
 description to r4
 ip address 10.1.34.1/30

router eigrp 101
 eigrp router-id 10.0.0.3
 network 0.0.0.0/0
 passive-interface lo
