frr version 8.5
frr defaults traditional
hostname rr1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! -------------------------------------------------------
! Node: rr1  (Route Reflector / P router)
! Role:  BGP route reflector for pe1 and pe2
!        IS-IS participant (not in forwarding path)
!
! Loopback:  10.0.0.1/32
! IS-IS NET: 49.0001.0000.0000.0001.00
! SR SID:    index 1  ->  label 16001  (SRGB base 16000)
! BGP AS:    65000    update-source lo
! -------------------------------------------------------
!
interface lo
 ip address 10.0.0.1/32
!
interface eth1
 description to P1
 ip address 10.1.0.6/30
!
interface eth2
 description to P2
 ip address 10.1.0.9/30
!
end
