frr version 8.4_git
frr defaults traditional
hostname edge1
service integrated-vtysh-config
interface lo
 ip address 10.251.255.11/32
interface eth1
 ip address 10.251.0.1/31
 ip ospf network point-to-point
interface eth2
 ip address 10.251.0.4/31
interface eth3
 ip address 192.0.2.0/31
router ospf
 ospf router-id 10.251.255.11
 passive-interface default
 no passive-interface eth1
 network 10.251.0.0/31 area 0
 network 10.251.255.11/32 area 0
 default-information originate always metric 10
 redistribute bgp metric 10 route-map INTERNET-ONLY
router bgp 65000
 bgp router-id 10.251.255.11
 no bgp ebgp-requires-policy
 neighbor 10.251.0.5 remote-as 65000
 neighbor 10.251.0.5 next-hop-self
 neighbor 192.0.2.1 remote-as 64501
 address-family ipv4 unicast
  neighbor 10.251.0.5 activate
  neighbor 192.0.2.1 activate
  neighbor 192.0.2.1 route-map ISP1-IN in
 exit-address-family
route-map ISP1-IN permit 10
 set local-preference 200
ip prefix-list INTERNET seq 10 permit 198.18.10.0/24
route-map INTERNET-ONLY permit 10
 match ip address prefix-list INTERNET
end
