client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
}
client authenticator {
    ipaddr = 192.168.99.1
    secret = testing123
    shortname = wired-authenticator
    nas_type = other
}
