frr version 8.5
frr defaults traditional
hostname r5
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.5/32
 ! TODO: ip router isis CORE
 ! TODO: isis passive

interface eth1
 ip address 10.1.35.2/30
 ! TODO: ip router isis CORE

! TODO: configure IS-IS
! r5 is Level-1 only, area 49.0002
! router isis CORE
!  net 49.0002.0100.0000.0005.00
!  is-type level-1
