frr version 8.5
frr defaults traditional
hostname attacker
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.10/32
!
interface eth1
 ip address 10.10.1.1/30
!
ip route 0.0.0.0/0 10.10.1.2
!
end
