frr version 8.5
frr defaults traditional
hostname r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 description to r1
 ip address 10.0.12.2/30
!
interface eth2
 description to r3
 ip address 10.0.23.1/30
!
router ospf
 router-id 10.0.0.2
 capability graceful-restart
 network 10.0.0.2/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.23.0/30 area 0
!
router bgp 65000
 bgp router-id 10.0.0.2
 bgp graceful-restart
 bgp graceful-restart restart-time 120
 bgp graceful-restart stalepath-time 360
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.3 remote-as 65000
 neighbor 10.0.0.3 update-source lo
 !
 address-family ipv4 unicast
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.3 activate
  network 10.0.0.2/32
 exit-address-family
!
end
