FROM smcline06/tacacs:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 \
    iputils-ping \
    procps \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
