frr defaults traditional
hostname isp
service integrated-vtysh-config
!
interface eth1
 ip address 198.18.108.2/24
 ipv6 address 2001:db8:ffff:108::2/64
!
interface eth2
 ip address 198.18.109.2/24
 ipv6 address 2001:db8:ffff:109::2/64
!
router bgp 65000
 bgp router-id 198.18.108.2
 no bgp ebgp-requires-policy
 neighbor 198.18.108.1 remote-as 65108
 neighbor 2001:db8:ffff:108::1 remote-as 65108
 address-family ipv4 unicast
  neighbor 198.18.108.1 activate
  network 198.18.109.0/24
 exit-address-family
 address-family ipv6 unicast
  neighbor 2001:db8:ffff:108::1 activate
  network 2001:db8:ffff:109::/64
 exit-address-family
!
ip route 198.18.108.0/24 Null0
ipv6 route 2001:db8:ffff:108::/64 Null0
line vty
