frr version 8.4_git
frr defaults traditional
hostname r1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 192.0.2.2/24
!
ip route 198.51.100.0/24 Null0
!
end
