frr version 8.4
frr defaults traditional
hostname enterprise
service integrated-vtysh-config
interface eth1
 ip address 198.18.70.11/24
interface eth2
 ip address 192.0.2.5/30
interface eth3
 ip address 10.100.70.1/30
interface eth4
 ip address 10.100.70.5/30
ip route 203.0.113.0/24 Null0
!
end
