frr version 8.4
frr defaults traditional
hostname r2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! -------------------------------------------------------
! Node: r2  (LSR — transit label switching router)
! Role:  OSPF underlay + LDP — configured by you
!
! Loopback:          10.0.0.2/32
! LDP router-id:     10.0.0.2
! Transport address: 10.0.0.2  (the loopback)
! -------------------------------------------------------
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 description to r1
 ip address 10.1.12.2/30
!
interface eth2
 description to r3
 ip address 10.1.23.1/30
!
end
