frr version 8.5
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.3/32
 ip ospf passive
 ip ospf area 0
!
interface eth1
 description to r2
 ip address 10.1.23.2/30
 ip ospf area 0
!
interface eth2
 description to r4
 ip address 10.1.34.1/30
 ip ospf area 0
!
router ospf
 ospf router-id 10.0.0.3
 area 2 stub
!
end
