frr version 8.4_git
frr defaults traditional
hostname p2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description to RR1
 ip address 10.1.0.10/30
exit
!
interface eth2
 description to P1
 ip address 10.1.0.14/30
exit
!
interface eth3
 description to PE2
 ip address 10.1.0.17/30
exit
!
interface lo
 ip address 10.0.0.5/32
exit
!
