frr version 8.5
frr defaults traditional
hostname bgp2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.4/32
!
interface eth1
 description to bgp1
 ip address 10.0.34.2/30
!
router bgp 65200
 no bgp ebgp-requires-policy
 neighbor 10.0.34.1 remote-as 65200
 address-family ipv4 unicast
  neighbor 10.0.34.1 activate
 exit-address-family
!
end
