options {
  directory "/var/cache/bind";
  listen-on { any; };
  listen-on-v6 { any; };
  recursion no;
};
zone "corp.example" { type master; file "/etc/bind/db.corp.example"; };
zone "10.10.108.10.in-addr.arpa" { type master; file "/etc/bind/db.108.10"; };
zone "8.b.d.0.1.0.0.2.ip6.arpa" { type master; file "/etc/bind/db.108.ip6"; };
