defaults {
    find_multipaths no
    user_friendly_names no
    polling_interval 1
}

devices {
    device {
        vendor "LIO-ORG"
        product "storage-lun"
        path_grouping_policy multibus
        path_selector "round-robin 0"
        path_checker tur
        failback immediate
        no_path_retry 12
    }
}
