[phones]
exten => 2001,1,NoOp(Enterprise voice call to phone A)
 same => n,Dial(PJSIP/2001,70)
 same => n,Hangup()

exten => 2002,1,NoOp(Enterprise voice call to phone B)
 same => n,Dial(PJSIP/2002,70)
 same => n,Hangup()
