[global]
type=global
user_agent=enterprise-voice-sip-qos

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=10.109.20.0/24
local_net=10.109.30.0/24
external_signaling_address=192.0.2.110
external_media_address=192.0.2.110
tos=cs3

[phone-template](!)
type=endpoint
context=phones
disallow=all
allow=ulaw
direct_media=no
rtp_symmetric=no
force_rport=yes
rewrite_contact=no
timers=no
tos_audio=ef
cos_audio=5

[aor-template](!)
type=aor
max_contacts=1
remove_existing=yes

[auth-a]
type=auth
auth_type=userpass
username=2001
password=voice-a-2001

[2001](phone-template)
auth=auth-a
aors=2001
callerid=Phone A <2001>

[2001](aor-template)

[auth-b]
type=auth
auth_type=userpass
username=2002
password=voice-b-2002

[2002](phone-template)
auth=auth-b
aors=2002
callerid=Phone B <2002>

[2002](aor-template)
