frr version 10.5.0
frr defaults traditional
hostname r3
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.3/32
 ip ospf area 0
!
interface eth1
 description OSPF point-to-point to r2
 ip address 10.1.23.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
router ospf
 ospf router-id 10.0.0.3
 passive-interface lo
!
end
