frr version 8.5
frr defaults traditional
hostname p1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
! -------------------------------------------------------
! Node: p1  (Provider Core)
! Role:  IS-IS + SR label forwarding only, no BGP
!
! Loopback:  10.0.0.4/32
! IS-IS NET: 49.0001.0000.0000.0004.00
! SR SID:    index 4  ->  label 16004  (SRGB base 16000)
! -------------------------------------------------------
!
interface lo
 ip address 10.0.0.4/32
!
interface eth1
 description to PE1
 ip address 10.1.0.2/30
!
interface eth2
 description to RR1
 ip address 10.1.0.5/30
!
interface eth3
 description to P2
 ip address 10.1.0.13/30
!
end
