frr version 8.5
frr defaults traditional
hostname spine
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.100/32

interface eth1
 ! Underlay link to vtep1 — 10.1.1.0/30
 ip address 10.1.1.2/30
 ip ospf area 0

interface eth2
 ! Underlay link to vtep2 — 10.1.2.0/30
 ip address 10.1.2.2/30
 ip ospf area 0

router ospf
 ospf router-id 10.0.0.100
 passive-interface lo

! BGP Route Reflector for L2VPN EVPN
! spine reflects EVPN routes between vtep1 and vtep2
router bgp 65000
 bgp router-id 10.0.0.100
 bgp cluster-id 10.0.0.100
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 !
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.1 update-source lo
 neighbor 10.0.0.1 route-reflector-client
 !
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 update-source lo
 neighbor 10.0.0.2 route-reflector-client
 !
 address-family l2vpn evpn
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.2 activate
 exit-address-family
