frr version 8.4_git
frr defaults traditional
hostname edge
service integrated-vtysh-config
interface lo
 ip address 10.250.255.31/32
interface eth1
 ip address 10.250.0.11/31
interface eth2
 ip address 10.250.0.13/31
interface eth3
 ip address 198.18.0.1/24
router ospf
 ospf router-id 10.250.255.31
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 network 10.250.0.10/31 area 0
 network 10.250.0.12/31 area 0
 network 198.18.0.0/24 area 0
 network 10.250.255.31/32 area 0
end
