frr version 8.5
frr defaults traditional
hostname r4
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.4/32

interface eth1
 ip address 10.1.34.2/30

router bgp 65004
 bgp router-id 10.0.0.4
 no bgp ebgp-requires-policy
 neighbor 10.1.34.1 remote-as 65003
 !
 address-family ipv4 unicast
  network 10.0.0.4/32
 exit-address-family
