frr version 8.5
frr defaults traditional
hostname spoke2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config

interface lo
 ip address 10.0.0.12/32
 ip address 192.168.2.1/24

interface dmvpn0
 ip address 172.16.0.12/24
 ip nhrp network-id 1
 ip nhrp nhs 172.16.0.1 nbma 10.0.0.1 multicast
 ip nhrp map 172.16.0.1 10.0.0.1
 ip ospf network point-to-point
 ip ospf area 0

router ospf
 router-id 10.0.0.12
 network 10.0.0.12/32 area 0
 network 192.168.2.0/24 area 0
 passive-interface lo
