frr version 8.4_git
frr defaults traditional
hostname internet-core
service integrated-vtysh-config
interface lo
 ip address 10.252.255.254/32
interface eth1
 ip address 192.0.2.5/31
interface eth2
 ip address 192.0.2.7/31
interface eth3
 ip address 198.18.10.1/24
router bgp 64500
 bgp router-id 10.252.255.254
 no bgp ebgp-requires-policy
 neighbor 192.0.2.4 remote-as 64501
 neighbor 192.0.2.6 remote-as 64502
 address-family ipv4 unicast
  network 198.18.10.0/24
  neighbor 192.0.2.4 activate
  neighbor 192.0.2.6 activate
 exit-address-family
end
